name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

env:
  MG_DEBUG: false
  DEVELOPER_NODE: 1

jobs:
  golangci:
    name: lint
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up latest Go 1.x version
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Get dependencies
        run: |
          go mod tidy
          cp .env.dist .env
      - name: Lint code with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          only-new-issues: true
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.13', '1.14', '1.15', '1.16']
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go mod tidy
          cp .env.dist .env
      - name: Tests
        run: go test -v ./... -cover -coverprofile=coverage.txt -covermode=atomic
      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash)
